feat: even better error messages

diff --git a/.github/workflows/update-config.yaml b/.github/workflows/update-config.yaml
--- a/.github/workflows/update-config.yaml
+++ b/.github/workflows/update-config.yaml
@@ -33,12 +33,12 @@ jobs:
       - name: Discover kustomization.yaml for ${{ env.APPLICATION_NAME }} in ${{ env.DEPLOY_TO_ENV }}
         id: discover
         run: |
-          #!/bin/bash
-
           result=$(find . -type f \( -name 'kustomization.yaml' -o -name 'kustomization.yml' \) -path "*/${DEPLOY_TO_ENV}/*" -path "*/${APPLICATION_NAME}/*" -exec dirname {} \; | sort | uniq)
-          if [ -z "$result" ] || [ $(echo "$result" | wc -l) -ne 1 ]; then
-            result=${result/$'\n'/%0A}
-            echo "::error title=Misconfigured config repository::Expected exactly one result. Found %0A${result}"
+          if [ -z "$result" ]; then 
+            echo "::error title=Misconfigured config repository::Expected exactly one kustomization.yaml, but found none. Please check configuration repo."
+            exit 1
+          elif [ $(echo "$result" | wc -l) -ne 1 ]; then
+            echo "::error title=Misconfigured config repository::Expected exactly one kustomization.yaml, but found multiple. Please check configuration repo."
             exit 1
           fi
 
